local=/psi.nfv.com/

# This file is used to configure the local DNS resolver for the OpenShift cluster.
# It maps the local IP address of the OpenShift cluster to the corresponding domain names.
# The IP address should be replaced with the actual IP address of the OpenShift cluster.

address=/*.apps.psi.nfv.com/10.0.111.61
address=/api.psi.nfv.com/10.0.111.61

# address=/oauth-openshift.apps.psi.nfv.com/10.0.111.61
# address=/console-openshift-console.apps.psi.nfv.com/10.0.111.61
# address=/grafana-openshift-monitoring.apps.psi.nfv.com/10.0.111.61
# address=/integrated-oauth-server-openshift-authentication.apps.psi.nfv.com/10.0.111.61
# address=/prometheus-k8s-openshift-monitoring.apps.psi.nfv.com/10.0.111.61
