- name: Get a deployed SNO server's floating IP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Dynamically include the 'make_iso' tasks from the 'psi-project' role
      ansible.builtin.include_role:
        name: cluster
        tasks_from: read_metadata

    - name: Dynamically include the 'read_metadata' tasks from the 'psi-project' role
      ansible.builtin.include_role:
        name: cluster
        tasks_from: get_server_fip.yml
