---
- name: Install an instance of Single Node OpenShift
  hosts: localhost
  gather_facts: false
  vars:
    keyname: "nextgen"
    cluster_name: "sno"
    cluster_domain: "sno.psi"
    cluster_ip: ""
    sno_image: "rhcos-live.iso"

  tasks:
    - name: Create SNO Openstack image
      openstack.cloud.image:
        cloud: psi
        name: "{{ cluster_name }}"
        state: present
        disk_format: iso
        container_format: bare
        filename: "{{ sno_image }}"
        tags:
          - nfv-sno
      register: image_info
