#!/bin/bash

# shellcheck disable=SC1091
. common_vars.sh

project_dir="proj-$PROJECT_NAME"

set -e

iso_dir=iso

ocp_arch=x86_64

iso_url=$(./openshift-install coreos print-stream-json | grep location | grep $ocp_arch | grep iso | cut -d\" -f4)

mkdir -p $iso_dir

if [ ! -f $iso_dir/"$SNO_ISO_IMAGE" ]; then
    echo "Downloading RHCOS ISO..."
    curl -L "$iso_url" -o $iso_dir/"$SNO_ISO_IMAGE"
else
    echo "RHCOS ISO already exists, skipping download."
fi

cp -f $iso_dir/"$SNO_ISO_IMAGE" .

if [ -d "$project_dir" ]; then
    echo "Removing existing directory: $project_dir"
    rm -rf "$project_dir"
fi

mkdir -p "$project_dir"

cp install-config.yaml "$project_dir"/install-config.yaml

./openshift-install --dir="$project_dir" create single-node-ignition-config

coreos-installer() {
    podman run --privileged --pull always --rm \
        -v /dev:/dev -v /run/udev:/run/udev -v "$PWD":/data \
        -w /data quay.io/coreos/coreos-installer:release "$@"
}

coreos-installer iso ignition embed -fi "$project_dir"/bootstrap-in-place-for-live-iso.ign "$SNO_ISO_IMAGE"