---
- name: Remove the sno network
  hosts: localhost
  gather_facts: false
  vars_files:
    - common_vars.yml

  tasks:
    - name: Delete server
      ansible.builtin.include_tasks:
        file: tasks/delete_sno_server.yml

    - name: Run tasks from tasks/delete_sno_net.yml
      ansible.builtin.include_tasks: tasks/delete_sno_net.yml

    - name: Run tasks from tasks/delete_os_net.yml
      ansible.builtin.include_tasks: tasks/delete_os_net.yml
