---

- name: Print hello world
  hosts: localhost
  vars:
    cluster_ip: "11.0.0.100/24"
  tasks:
    - name: Read cluster configuration
      ansible.builtin.include_vars:
        file: clusters.yml

    - name: Iterate over clusters variable and build dictionary of items
      ansible.builtin.set_fact:
        cluster_dict: >-
          {{
            cluster_dict | default({}) |
            combine(
              {item.value.domain: [ item ]},
              recursive=true,
              list_merge='append_rp'
            )
          }}
      loop: "{{ clusters | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Print cluster_dict
      ansible.builtin.debug:
        var: cluster_dict

    - name: Print cluster_dict
      ansible.builtin.debug:
        var: item
      loop: "{{ cluster_dict | dict2items }}"

    - name: Test reverse DNS
      ansible.builtin.debug:
        msg:
          - "{{ cluster_ip | ansible.utils.ipaddr('address') | split('.') | reverse | join('.') }}.in-addr.arpa."
          - "{{ (cluster_ip | ansible.utils.ipaddr('address') | split('.') | reverse)[1:] | join('.') }}.in-addr.arpa."
