---
- name: Create/attach floating IP to the sno network server interface on {{ project_instance_ip }}  # noqa name[template]
  openstack.cloud.floating_ip:
    state: present
    reuse: true
    floating_ip_address: 10.0.108.218
    server: "{{ project_name }}" # Name of the server to associate FIP with
    network: "{{ project_provider_network }}" # External network to allocate FIP from
    nat_destination: "{{ project_name }}" # NAT destination for the floating IP
    fixed_address: "{{ project_instance_ip }}"
    wait: true
    timeout: 120
  register: floating_ip_result

- name: Create/attach floating IP to the openstack network server interface on {{ project_instance_ip_os }}
  openstack.cloud.floating_ip:
    state: present
    reuse: true
    server: "{{ project_name }}"
    network: "{{ project_provider_network }}"
    nat_destination: "{{ project_name }}-os"
    fixed_address: "{{ project_instance_ip_os }}"
    wait: true
    timeout: 180
  register: floating_ip_result_os

- name: Display Floating IP
  ansible.builtin.debug:
    msg:
      - "Allocated/Associated os net floating IP: {{ floating_ip_result_os.floating_ip.floating_ip_address }}"
      - "Allocated/Associated sno net floating IP: {{ floating_ip_result.floating_ip.floating_ip_address }}"
  when: floating_ip_result.floating_ip.floating_ip_address is defined
