# Corresponds to the volume creation part
- name: "Get sno port information"
  openstack.cloud.port_info:
    name: "{{ project_name }}"
  register: sno_port_result

- name: "Get OS port information"
  openstack.cloud.port_info:
    name: "{{ project_name }}-os"
  register: os_port_result

- name: Fail if either port is not defined
  ansible.builtin.fail:
    msg: "Either the SNO port or OS port is missing. Please check the configuration."
  when: sno_port_result.ports is not defined or sno_port_result.ports | length != 1 or
        os_port_result.ports is not defined or os_port_result.ports | length != 1

- name: Ensure bootable volume {{ project_name }} exists # noqa name[template]
  openstack.cloud.volume:
    state: present
    size: "{{ sno_volume_size }}"
    name: "{{ project_name }}"
    bootable: true
    wait: true
    timeout: 300
  register: volume_result

# Corresponds to the server creation part
- name: Ensure server {{ project_name }} exists # noqa name[template]
  openstack.cloud.server:
    name: "{{ project_name }}"
    auto_ip: false
    state: present
    image: "{{ project_iso_image }}" # The image to install/boot on the volume
    flavor: "{{ sno_flavor }}"
    volumes:
      - "{{ project_name }}" # Name of the volume to attach
    nics:
      - port-id: "{{ sno_port_result.ports[0].id }}" # Attach the pre-created port
      - port-id: "{{ os_port_result.ports[0].id }}" # Attach the pre-created OS port
    security_groups: # Explicitly associate security group with server
      - "{{ psi_sno_sg_sno }}"
      - "{{ psi_sno_sg_openstack }}"
      - default
    # key_name: "your-ssh-key-name" # Optional: if you want to inject an SSH key
    # user_data: "{{ lookup('file', 'cloud-init-config.yaml') }}" # Optional: for cloud-init
    wait: true # Wait for the server to become active
    timeout: 600 # Timeout for waiting (adjust as needed)
  register: server_result
  when: volume_result.volume.id is defined and port_result.port.id is defined # Ensure dependencies are met

- name: Display Server Information
  ansible.builtin.debug:
    msg: >
      Server {{ server_result.server.name | default('N/A') }} is active.
      Instance ID: {{ server_result.server.id | default('N/A') }}.
      Floating IP (if associated): {{ floating_ip_result.floating_ip.floating_ip_address | default('Not associated or FIP task skipped') }}.
      Fixed IP: {{ project_instance_ip }}.
  when: server_result.server is defined
