- name: Output calculated instance IP for verification
  ansible.builtin.debug:
    msg: "Calculated instance IP: {{ project_instance_ip_os }}"

- name: "Ensure internal network exists {{ project_name }}-os" # noqa name[template]
  openstack.cloud.network:
    state: present
    name: "{{ project_name }}-os"
  register: network_info

- name: "Display network creation/update information"
  ansible.builtin.debug:
    var: network_info
  when: network_info is changed or ansible_verbosity > 0

- name: "Ensure subnet exists on network"
  openstack.cloud.subnet:
    state: present
    name: "{{ project_name }}-os"
    network_name: "{{ project_name }}-os"
    cidr: "{{ project_openstack_cidr }}"
    dns_nameservers: "{{ dns_fip }}"
  register: subnet_info

- name: "Display subnet creation/update information"
  ansible.builtin.debug:
    var: subnet_info
  when: subnet_info is changed or ansible_verbosity > 0

- name: "Ensure external router exists for the openstack network" # noqa name[template]
  openstack.cloud.router:
    state: present
    name: "{{ psi_sno_router_openstack }}"
    network: "{{ project_provider_network }}" # Sets the external gateway
    interfaces:
      - net: "{{ project_name }}-os"
        subnet: "{{ project_name }}-os"
      # enable_snat: true # Default is true, explicitly set if needed
  register: router_info

- name: "Final configuration summary"
  ansible.builtin.debug:
    msg:
      - "Router '{{ router_info.router.name }}' configured."
      - "External gateway set to '{{ router_info.router.external_gateway_info }}'."
      - "Internal network '{{ project_name }}-os' with subnet '{{ project_name }}-os' ({{ project_openstack_cidr }}) created."

- name: "Create port on network with default security group"
  openstack.cloud.port:
    state: present
    name: "{{ project_name }}-os"
    network: "{{ project_name }}-os"
    fixed_ips:
      - subnet: "{{ project_name }}-os" # Name of the subnet
        ip_address: "{{ project_instance_ip_os }}"
    security_groups:
      - "{{ psi_sno_sg_openstack }}"  # This is the security group created above
  register: port_info

- name: "Display port creation/update information"
  ansible.builtin.debug:
    var: port_info
  when: port_info is changed or ansible_verbosity > 0
