---
- name: "Create a temporary file for the rendered Butane config for {{ current_butane_template_file_info.path | basename }}"
  ansible.builtin.tempfile:
    state: file
    suffix: .bu
  register: rendered_butane_tempfile

- name: "Render Butane template: {{ current_butane_template_file_info.path }}"
  ansible.builtin.template:
    src: "{{ current_butane_template_file_info.path }}" # Full path to the .j2 file
    dest: "{{ rendered_butane_tempfile.path }}"
    mode: '0644'

- name: "Generate Ignition for {{ current_butane_template_file_info.path | basename }}"
  vars:
    # Input template filename without .j2 extension
    base_filename: "{{ current_butane_template_file_info.path | basename | regex_replace('\\.j2$', '') }}"
    # Output Ignition filename
    output_ign_filename: "{{ ignition_output_dir }}/{{ base_filename | splitext | first }}.ign"
  ansible.builtin.command:
    cmd: >
      {{ butane_executable }}
      --strict
      --raw
      {{ rendered_butane_tempfile.path }}
      -o {{ output_ign_filename }}
  register: butane_execution_result
  changed_when: butane_execution_result.rc == 0
  failed_when: butane_execution_result.rc != 0

- name: "Generate MachineConfig for {{ current_butane_template_file_info.path | basename }}"
  vars:
    # Input template filename without .j2 extension
    base_filename: "{{ current_butane_template_file_info.path | basename | regex_replace('\\.j2$', '') }}"
    # Output Ignition filename
    output_ign_filename: "{{ ignition_output_dir }}/{{ base_filename | splitext | first }}.yaml"
  ansible.builtin.command:
    cmd: >
      {{ butane_executable }}
      --strict
      {{ rendered_butane_tempfile.path }}
      -o {{ output_ign_filename }}
  register: butane_execution_result
  changed_when: butane_execution_result.rc == 0
  failed_when: butane_execution_result.rc != 0

- name: "Display butane execution standard output for {{ current_butane_template_file_info.path | basename }}"
  ansible.builtin.debug:
    var: butane_execution_result.stdout
  when: butane_execution_result.stdout | default('') | length > 0 and (ansible_verbosity > 0 or butane_execution_result.rc != 0)

- name: "Display butane execution standard error for {{ current_butane_template_file_info.path | basename }}"
  ansible.builtin.debug:
    var: butane_execution_result.stderr
  when: butane_execution_result.stderr | default('') | length > 0 and (ansible_verbosity > 0 or butane_execution_result.rc != 0)

- name: "Clean up temporary rendered Butane file for {{ current_butane_template_file_info.path | basename }}"
  ansible.builtin.file:
    path: "{{ rendered_butane_tempfile.path }}"
    state: absent
  when: rendered_butane_tempfile.path is defined
