kind: PersistentVolume
apiVersion: v1
metadata:
  name: "local-storage-mariadb-pv"
  annotations:
    pv.kubernetes.io/provisioned-by: psi-devsetup
  labels:
    provisioned-by: psi-devsetup
    service: mariadb
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: "/mnt/openstack/pv2"
    type: DirectoryOrCreate
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["REPLACE_WITH_NODE_NAME"]