---
- name: Start Playbook
  hosts: all
  gather_facts: false
  remote_user: core
  vars_files:
    - common_vars.yml

  tasks:
    - name: Read project metadata
      ansible.builtin.include_tasks: tasks/read_metadata.yml

    - name: Include tasks
      ansible.builtin.include_tasks: tasks/start_cluster.yml
