---
- name: Ensure SNO security group exists {{ project_name }}
  openstack.cloud.security_group:
    state: present
    name: "{{ psi_sno_sg_sno }}"
    description: "Security group for {{ project_name }}"
    security_group_rules:
      - protocol: icmp
        remote_ip_prefix: "0.0.0.0/0"  # Allow from anywhere
        description: "Allow ICMP"
        direction: ingress
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "0.0.0.0/0"
        description: "SSH access"
        direction: ingress
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: "0.0.0.0/0"
        description: "HTTP access"
        direction: ingress
      - protocol: tcp
        port_range_min: 443
        port_range_max: 443
        remote_ip_prefix: "0.0.0.0/0"
        description: "HTTPS access"
        direction: ingress
      - protocol: tcp
        port_range_min: 6443
        port_range_max: 6443
        remote_ip_prefix: "0.0.0.0/0"
        description: "Kubernetes API access"
        direction: ingress
      - protocol: tcp
        port_range_min: 22623
        port_range_max: 22623
        remote_ip_prefix: "0.0.0.0/0"
        description: "Machine Config Server access"
        direction: ingress

- name: "Create VXLAN security group for the OS network"
  openstack.cloud.security_group:
    state: present
    name: "{{ psi_sno_sg_openstack }}"  # This is the default security group name in OpenStack
    description: "VXLAN security group"
    security_group_rules:
      - protocol: tcp
        port_range_min: 4789
        port_range_max: 4789
        remote_ip_prefix: "0.0.0.0/0"  # Allow from anywhere
        direction: ingress
