- name: Delete server {{ project_name }} 
  openstack.cloud.server:
    name: "{{ project_name }}"
    state: absent

- name: Delete bootable volume {{ project_name }}
  openstack.cloud.volume:
    state: absent
    name: "{{ project_name }}"
