#!/bin/bash

set -eo pipefail

# shellcheck disable=SC1091
. scripts/common_vars

project_dir="proj-$PROJECT_NAME"

set -e

iso_download_dir=iso

ocp_arch=x86_64

iso_url=$(openshift-install coreos print-stream-json | grep location | grep $ocp_arch | grep iso | cut -d\" -f4)

printf "ISO URL: %s\n" "$iso_url"

mkdir -p $iso_download_dir

if [ ! -f $iso_download_dir/"$SNO_ISO_IMAGE" ]; then
    echo "Downloading RHCOS ISO... to $iso_download_dir/$SNO_ISO_IMAGE"
    curl -L "$iso_url" -o $iso_download_dir/"$SNO_ISO_IMAGE"
else
    echo "RHCOS ISO already exists, skipping download."
fi

cp -f $iso_download_dir/"$SNO_ISO_IMAGE" .

if [ -d "$project_dir" ]; then
    echo "Removing existing directory: $project_dir"
    rm -rf "$project_dir"
fi

mkdir -p "$project_dir"

cp install-config.yaml "$project_dir"/install-config.yaml

openshift-install --dir="$project_dir" create single-node-ignition-config

coreos-installer() {
    set -o xtrace
    podman run --privileged --pull always --rm \
        -v /dev:/dev -v /run/udev:/run/udev -v "$PWD":/data \
        -w /data quay.io/coreos/coreos-installer:release "$@"
    set +o xtrace
}

coreos-installer iso ignition embed -fi "$project_dir"/bootstrap-in-place-for-live-iso.ign "$SNO_ISO_IMAGE"

openstack image delete "$SNO_ISO_IMAGE"
openstack image create --container-format bare --disk-format iso --progress --file "$SNO_ISO_IMAGE" "$SNO_ISO_IMAGE"
