---
- name: Output calculated instance IP for verification
  ansible.builtin.debug:
    msg: "Calculated instance IP: {{ project_instance_ip }}"

# Corresponds to the security_groups() function logic
- name: Ensure network {{ project_name }} exists # noqa name[template]
  openstack.cloud.network:
    state: present
    name: "{{ project_name }}"
  register: network_result

- name: Ensure subnet {{ project_name }} exists on network {{ project_name }} # noqa name[template]
  openstack.cloud.subnet:
    state: present
    network_name: "{{ project_name }}"
    name: "{{ project_name }}"
    cidr: "{{ project_cidr }}"
    dns_nameservers:
      - "{{ dns_fip }}"
  register: subnet_result

- name: "Add interface to the sno networks router"
  openstack.cloud.router:
    state: present
    name: "{{ project_name }}"
    network: "{{ project_provider_network }}"
    interfaces:
      - net: "{{ project_name }}"
        subnet: "{{ project_name }}"
  register: router_interface_info
  when: subnet_result.subnet is defined # Ensure parent resources exist

- name: Ensure port {{ project_name }} exists with fixed IP {{ project_instance_ip }} # noqa name[template]
  openstack.cloud.port:
    state: present
    name: "{{ project_name }}"
    network: "{{ project_name }}" # Name of the network
    security_groups:
      - "{{ psi_sno_sg_sno }}"
      - default
    fixed_ips:
      - subnet: "{{ project_name }}" # Name of the subnet
        ip_address: "{{ project_instance_ip }}"
  register: port_result
