---
- name: Build the PSI Project ISO using include_role and tasks_from
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../inventory/group_vars/all.yml

  tasks:
    - name: Dynamically include the 'make_iso' tasks from the 'openshift/iso-builder' role
      ansible.builtin.include_role:
        name: openshift/iso-builder
        tasks_from: make_iso
