#!/bin/bash

BRIDGE_NAME="${BRIDGE_NAME:-bridge-main}"

gen_short_name() {
  local ns_cidr=$1

  local ns_ip="${ns_cidr/\/*}"

  sed -rn 's/.*\.([0-9]*\.[0-9]*)$/\1/p' <<< "$ns_ip"

  ns_name="${ns_ip//./_}"
}

# ns_name=blue
# ns_cidr=192.168.60.15/16
# bridge_ip=192.168.60.16
setup_ns() {
  local ns_cidr=$1
  local bridge_ip=$2

  if [[ -z "$ns_cidr" || -z "$bridge_ip" ]]; then
    echo "Usage: setup_ns <ns_cidr> <bridge_ip>"
    return 1
  fi
  # Check if the namespace already exists
  if ip netns list | grep -q "$ns_name"; then
    echo "Namespace $ns_name already exists. Skipping creation."
    return 0
  fi

  ns_ip="${ns_cidr/\/*}"
  ns_name=$(gen_short_name "$ns_ip")

  # create a new network namespace named “blue” on Host-2
  sudo ip netns add "$ns_name"

  # Create a virtual Ethernet pair (veth) interface, “blue-in” and “blue-out,” and move “blue-in” into the “blue” namespace
  sudo ip link add "$ns_name-in" type veth peer name "$ns_name-out"
  sudo ip link set "$ns_name-in" netns "$ns_name"

  # Configure the IP address and bring up the “blue-in” interface in the “blue” namespace:
  sudo ip netns exec "$ns_name" ip addr add "$ns_cidr" dev "$ns_name-in"
  sudo ip netns exec "$ns_name" ip link set "$ns_name-in" up

  sudo ip link set "$ns_name-out" master "$BRIDGE_NAME"
  sudo ip link set "$ns_name-out" up

  sudo ip netns exec "$ns_name" ip route add default via "$bridge_ip"
}

check_bridge() {
  # Check if the bridge already exists
  if ip link show "$BRIDGE_NAME" &>/dev/null; then
    return 0
  fi

  return 1
}

get_bridge_cidr() {
  cidr=$(ip a show bridge-main | sed -rn 's/.*inet\s+([^ ]*).*/\1/p')

  return "$cidr"
}

# bridge_name=bridge-main
# ip_cidr=192.168.60.16/16
setup_bridge() {
  local ip_cidr=$2

  if [[ -z "$ip_cidr" ]]; then
    echo "Usage: setup_bridge <ip_cidr>"
    return 1
  fi
  # Check if the bridge already exists
  if ip link show "$BRIDGE_NAME" &>/dev/null; then
    echo "Bridge $BRIDGE_NAME already exists. Skipping creation."
    return 0
  fi

  sudo ip link add "$BRIDGE_NAME" type bridge
  sudo ip addr add "$ip_cidr" dev "$BRIDGE_NAME"
  sudo ip link set "$BRIDGE_NAME" up
}

setup_vxlan() {
  local vxlan_id=$1
  local local_ip=$2
  local remote_ip=$3
  local dev=$4

  tname=$(gen_short_name "$remote_ip")

  if [[ -z "$vxlan_id" || -z "$local_ip" || -z "$remote_ip" || -z "$dev" ]]; then
    echo "Usage: setup_vxlan <vxlan_id> <local_ip> <remote_ip> <dev>"
    return 1
  fi
  # Check if the vxlan interface already exists
  if ip link show "vxlan-$tname" &>/dev/null; then
    echo "VXLAN interface vxlan-$tname already exists. Skipping creation."
    return 0
  fi
  # Create the vxlan interface
  sudo ip link add "vxlan-$tname" type vxlan id "$vxlan_id" local "$local_ip" remote "$remote_ip" dstport 4789 dev "$dev"
  sudo ip link set "vxlan-$tname" master "$BRIDGE_NAME"
  sudo ip link set "vxlan-$tname" up
}

del_bridge_all() {  # Remove the bridge
  readarray -t ports < <(sudo bridge link show master "$BRIDGE_NAME" | sed -nr 's/^[^ ]* ([^:]*).*/\1/p')

  # Remove all ports from the bridge
  for port in "${ports[@]}"; do
    port=$(sed -rn 's/(.*)*.*/\1/p' <<<"$port")
    # Remove the interface from the bridge and delete it
    sudo ip link set "$port" down
    sudo ip link set "$port" nomaster
    sudo ip link del "$port"
  done
  # Remove the bridge
  sudo ip link set "$BRIDGE_NAME" down
  sudo ip link del "$BRIDGE_NAME"
}

del_bridge_veth() {
  local veth_name=$1
  # Remove the interface from the bridge and delete it
  sudo ip link set "$veth_name" down
  sudo ip link set "$veth_name" nomaster
  sudo ip link del "$veth_name"
}

del_tunnel() {
  local tunnel_name=$1
  # Remove the interface from the bridge and deleie it
  sudo ip link set "$tunnel_name" down
  sudo ip link set "$tunnel_name" nomaster
  sudo ip link del "$tunnel_name"
}

test_it() {
  bridge_cidr="192.168.60.16/16"

  setup_bridge "$BRIDGE_NAME" "$bridge_cidr"
  setup_ns "192.168.60.15/16" "${bridge_cidr/\/*}"
  setup_vxlan "100" "192.168.1.90" "192.168.1.2" "eno1"
}

add_tunnel() {
  local ns_cidr=$1
  local vxlan_id=$2
  local local_ip=$3
  local remote_ip=$4
  local dev=$5

  if ! check_bridge; then
    echo "Bridge $BRIDGE_NAME does not exist. Please create it first ($0 install-bridge)."
    return 1
  fi

  bridge_cidr=$(get_bridge_cidr)
  if [[ -z "$bridge_cidr" ]]; then
    echo "Error getting $BRIDGE_NAME address!"
    return 1
  fi

  setup_ns "$ns_cidr" "${bridge_cidr/\/*}"
  setup_vxlan "$vxlan_id" "$local_ip" "$remote_ip" "$dev"
}

while getopts ":hv" opt; do
    case ${opt} in
    v)
        VERBOSE="true"
        ;;
    h)
        usage
        exit 0
        ;;
    \?)
        echo "Invalid Option: -$OPTARG" 1>&2
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

if [ "$#" -gt 0 ]; then
    COMMAND=$1
    shift
else
    COMMAND="help"
fi

if [ "$VERBOSE" == "true" ]; then
    set -x
fi

case "$COMMAND" in
install-bridge)
    setup_bridge "$@"
    ;;
add-tunnel)
    add_tunnel "$@"
    ;;
esac
